### ISSUE TITLE
Make curl-dir look more like other file tasks

### ISSUE THREAD

**Issue by ffissore** [twolfson/grunt-curl#27]
In an attempt to make curl-dir work with `grunt-if-missing`, I've opened an issue (see https://github.com/tests-always-included/grunt-if-missing/issues/1) and the problem is with the special syntax used by `curl-dir`
Even the attempts I've made hit the wall of curl-dir task structure: running `grunt.task.normalizeMultiTaskFiles` on it returns an empty fileset.
It would be nice if curl-dir used a structure like http://gruntjs.com/configuring-tasks#globbing-patterns

**Comment by twolfson** [comment]
I think this issue has been resolved. Closing it for now.
