### ISSUE TITLE
Error while running grunt-curl

### ISSUE THREAD

**Issue by sharmagourav** [twolfson/grunt-curl#30]
hi , I am trying to set up this grunt-curl on my project. I am getting this erro while running this on my Web (.Net) application. could you please help me out.
Running "curl:http://localhost:61115/dev/" (curl) task
Verifying property curl.http exists in config...ERROR
>> Unable to process task.
Warning: Required config property "curl.http" missing. Use --force to continue.

this is my code: 
'use strict';
module.exports = function (grunt) {

    // Configure `curl` with URLs
    // If you would like to download multiple files
    // to the same directory, there is `curl-dir`
    grunt.initConfig({
        curl : {
            'http://localhost:61115/dev/': 'http://aa.com/artifactory/api/npm/npm-local/'
        }
    });

    // Load in `grunt-curl`
    grunt.loadNpmTasks('grunt-curl');
};

I am very new to grunt , so you can expect a preety minor issue too. :+1:

**Comment by twolfson** [comment]
It looks like `grunt` is choking on the full URL. Please try running `grunt curl` from the command line instead.

**Comment by sharmagourav** [comment]
thanks for respond. I am runnly through command prompt only. Is there any other way to run it ?

**Comment by twolfson** [comment]
I think we are missing each other. Let's start over. What program are you running the command from (e.g. `cmd.exe`, Powershell), what is the command you are running (e.g. `grunt default`), what version of `grunt`, `grunt-cli`, and `grunt-curl` are you using (found via `npm ls`)?

**Comment by sharmagourav** [comment]
i am using node.js command promt and  'grunt curl' as command. Grunt version : 0.4.5 grunt-cli : 0.1.13 grunt-curl : 2.0.3

**Comment by twolfson** [comment]
What do you mean by node.js command prompt? Can you send me a screenshot?

**Comment by sharmagourav** [comment]
Here you go.!!

[cid:image003.jpg@01D02F3A.05B43850]

[cid:image004.jpg@01D02F3A.05B43850]



Thanks,
Gourav Sharma | Systems Engineer | Ameriprise Financial

**Comment by twolfson** [comment]
Those aren't showing up in GitHub. Please add them via the GitHub UI, not as email attachments =/

**Comment by sharmagourav** [comment]
![node](https://cloud.githubusercontent.com/assets/10505556/5728484/2b8b3486-9b30-11e4-9bad-5b97d8830b01.jpg)
![nodels](https://cloud.githubusercontent.com/assets/10505556/5728486/2fdb7320-9b30-11e4-9c76-0834da7d2757.JPG)

**Comment by twolfson** [comment]
Ooooh, I have it. You are specifying the destination as `http://localhost:61115/dev/` which is not a valid filepath on your filesystem. Try a config like:

```js
'localhost/dev.html': 'http://aa.com/artifactory/api/npm/npm-local/'
```

**Comment by sharmagourav** [comment]
Hey..

Thanks a lot. It worked.

Thanks,
Gourav Sharma | Systems Engineer | Ameriprise Financial
