### ISSUE TITLE
username and password for curl

### ISSUE THREAD

**Issue by whbath** [twolfson/grunt-curl#32]
How do you add in username and password details ala --user user:pass ?

**Comment by twolfson** [comment]
These can be added by using `src` as if it were `request` parameters:

https://github.com/twolfson/grunt-curl/tree/2.2.0#using-request-options

https://github.com/request/request/tree/v2.55.1#http-authentication

```js
src: {
  url: 'http://google.com',
  auth: {
    username: 'foo',
    password: 'bar'
  }
}
```

**Comment by whbath** [comment]
Great, thanks for the quick turn around!
