### ISSUE TITLE
Add configuration option for customizing error condition

### ISSUE THREAD

**Issue by egeste** [twolfson/grunt-curl#35]
Currently, this project uses a hard-coded failure condition based on the response' HTTP STATUS code as follows:

```javascript
if (statusCode < 200 || statusCode >= 300) {
  return cb(new Error('Fetching ' + JSON.stringify(options) + ' failed with HTTP status code ' + statusCode));
}
```

This causes the grunt task runner to stop executing tasks post-error  if not run with the `-f` or `--force` flag, and prevents the current executing method from completing its implementation. This is problematic when doing something like the following:

```coffeescript
curl:
  geodatasource_cities_auth:
    src:
      url: 'http://www.geodatasource.com/login'
      method: 'POST'
      formData:
        password: 'password'
        emailAddress: 'email@example.com'
      jar: true
    dest: '/dev/null'
  geodatasource_cities_free:
    src:
      url: 'http://www.geodatasource.com/download?id=8'
      jar: true
    dest: 'seed/geodatasource_cities_free.zip'
```

Where the `geodatasource_cities_auth` task returns an HTTP STATUS 302; a success condition in this scenario.

Please add some kind of configuration option to ignore warnings/errors or specify permissible status codes outside of the 200 block.

**Comment by twolfson** [comment]
Can you explain your use case further? I don't fully grasp why we want to support a 302 request -- this task is usually intended to download content.

**Comment by egeste** [comment]
Sure. In this particular use case, I'm making two requests. The first is an authentication request, POSTing my credentials to the server. I'm using the plugin's ability to take `request` options to specify `jar: true` to cache the resulting authentication cookies. Subsequently, in the second request, I also specify `jar: true` to use the cookies set in the previous request, which then permits me to access the resource I'm attempting to download.

**Comment by twolfson** [comment]
I think that usage is bending the purpose of this tool a bit. With the requirement of sharing global state, it feels like that should be handle by a custom script or a library better fit for making successive requests. Going to decline this request for now =/
