### ISSUE TITLE
custom request options in curl-dir cause parse error

### ISSUE THREAD

**Issue by solazs** [twolfson/grunt-curl#36]
Hi!
I've just run into a problem and I'm pretty sure it's a bug.

I'm trying to use curl-dir, but need to send a cookie as well. Part of my gruntfile:

``` javascript

        'curl-dir': {
            validation: {
                src: [
                    {
                        url: backendUrl + "/patches/meta",
                        cookie: apiToken
                    },
                    {
                        url: backendUrl + "/devices/meta",
                        cookie: apiToken
                    }
                ],
                dest: 'lib/validation-rules'
            }
        }

```

Execution of the task stops with an error (verbose output):

```
Running "curl-dir:validation" (curl-dir) task
Verifying property curl-dir.validation exists in config...OK
Warning: Object #<Object> has no method 'indexOf' Use --force to continue.
```

If only strings are given in the src array it works fine, but according to the [docs](https://github.com/twolfson/grunt-curl#using-request-options-1) this should work as well.

**Comment by twolfson** [comment]
That looks like it should work. We support arrays of requests for `curl-dir`:

https://github.com/twolfson/grunt-curl/blob/2.2.0/tasks/curl.js#L76-L97

as well as test it:

https://github.com/twolfson/grunt-curl/blob/2.2.0/test/grunt.js#L77-L84

However, I don't see any `cookie` option as a parameter for `request`. Can you try passing it via request headers?

```js
        'curl-dir': {
            validation: {
                src: [
                    {
                        url: backendUrl + "/patches/meta",
                        headers: {
                            Cookie: apiToken
                        }
                    },
                    {
                        url: backendUrl + "/devices/meta",
                        headers: {
                            Cookie: apiToken
                        }
                    }
                ],
                dest: 'lib/validation-rules'
            }
        }
```

**Comment by solazs** [comment]
Thanks for the quick reply. 
Prior to opening this issue I've tried sending the cookies as headers too, with the same result, though I now realize that cookies are handled differently.

However 
```javascript
        'curl-dir': {
            validation: {
                src: [
                    {
                        url: backendUrl + "/ips/meta"
                    }
                ],
                dest: 'lib/validation-rules'
            }
        }
```

results in the error described above, too.

**Comment by twolfson** [comment]
Hmm, weird. For reference, what version of `node`, `grunt`, and `grunt-curl` are you using?

```bash
node --version
npm ls grunt
npm ls grunt-curl
```

**Comment by solazs** [comment]
node.js: 0.10.25 (from ubuntu repo)
grunt: 0.4.5
grunt-curl: 2.2.0

However this issue was restricted to my config only, it worked fine on my colleague's desktop and our deployment server. Turns out I had some other node.js-related issues, so the problem must be on my end.
I think this must be related to the really old node.js used. I'm in the process of updating, I'll report back later this week if the issue is still present.

**Comment by twolfson** [comment]
Weird. Alright, closing issue for now. Thanks for being so responsive =)

**Comment by solazs** [comment]
Hi, just reporting back. 
Issue was not with grunt-curl, my setup was broken, sorry for the inconvenience!
