### ISSUE TITLE
Add authentication to the request

### ISSUE THREAD

**Issue by lynchmaniac** [twolfson/grunt-curl#38]
Is there a way to add authentication in the request ?

```
        test: {
            src: {
                url: 'http://localhost/nexus/service/local/artifact/maven/resolve?r=repo&g=fr.test&a=AAA&v=1.0.1-SNAPSHOT&e=apk',
                auth: {
                    user: 'user',
                    pass: 'mdp'
                }
            },
            dest: 'toto.apk'
        }
```
doesn't seems to work well.
This example is based on the request module.

If there is a way i think it's pretty cool to show an example in the readme. 

grunt-curl 2.2.0
node 6.9.1
npm 3.10.8

**Comment by twolfson** [comment]
Based on this issue being closed, I'm guessing you worked out the solution. The syntax all looks correct so I'm guessing it was a server-side issue:

https://github.com/request/request/tree/v2.81.1#http-authentication

**Comment by lynchmaniac** [comment]
yeah exactly, i've made a PR if you want to add an example in the Readme.
